### PR TITLE
Setup/themes directory

### PR DESCRIPTION
**Pull request by makss**
For test use, do not apply the patch.

---
* Move default theme to separate directory `setup/themes/default`
* Introduce **Fantastic Empty theme** `setup/themes/empty`
* Allow configure import data and articles. Option 'txp-data' in `manifest.json`:
    * `<default>` - Import /articles and /data from setup dir
    * `'theme'` - Import /articles and /data from theme dir
    * `'none'`  - Nothing to import.

### CODE REVIEW

**Comment by bloatware** [comment]
Euh... haven't we decided "no themes in setup dir"? Just something more informative than the current "Unknown section" text in case no theme is installed?

**Comment by bloatware** [comment]
No worries, it's [here](https://forum.textpattern.io/viewtopic.php?pid=307417#p307417). I have skipped the whole themes branch, sorry, but doesn't a click on "Create new theme" button already create a new empty theme?

**Comment by makss** [comment]
> I have skipped the whole themes branch, sorry, but doesn't a click on "Create new theme" button already create a new empty theme?

Wow! It works, unexpectedly, Thanks!

Only to see this I had to [fix bug](https://github.com/textpattern/textpattern/pull/955).
BTW, last time I also could not open the theme branch until I corrected the [error](https://github.com/textpattern/textpattern/pull/940).

I wonder what will happen if I go back in the themes again? ;-)

**Comment by bloatware** [comment]
I'm sure you'll be welcomed!

**Comment by philwareham** [comment]
Hi all! What's the status on this pull request? I am fairly keen to merge the themes branch into dev and continue any theme improvements directly in the dev branch. Cheers!

**Comment by makss** [comment]
I will periodically update the setup section, I hope this will speed up the testing and merge brunch `themes`.

**Pull request merged**
