### PR TITLE
Remove broken import functionality

### PR DESCRIPTION
**Pull request by vanmelick**
Fix issue #557

### CODE REVIEW

**Comment by philwareham** [comment]
The language strings will needs to keep the import strings for now, so please revert that part of the change.

FYI the language text files we are planning to bundle into v4.7 release, so we will redux them at that point.

**Comment by vanmelick** [comment]
Do you mean en-gb.php AND en-gb.txt or just one of these?

**Comment by philwareham** [comment]
Both of those need to left untouched for now. Thanks!

**Comment by vanmelick** [comment]
Lang file changes are reverted.

**Comment by philwareham** [comment]
Thanks Ruud!

**Pull request merged**
