### PR TITLE
Small changes to the setup SQL

### PR DESCRIPTION
**Pull request by petecooper**
* Remove About - it's pointless if it's empty
* Remove textgarden.org link
* Fix typos in the markup comments

### CODE REVIEW

**Comment by philwareham** [comment]
Any changes to public theme files will need to be done in its own repo, not the Textpattern master branch.

https://github.com/textpattern/textpattern-default-theme

**Comment by petecooper** [comment]
Ah, makes sense - will close and resubmit.

**Comment by philwareham** [comment]
Basically, please remove the comment typos from this PR. Put those in the other repo (since that is where I build the public theme from).

Everything else looks good to me.

Thanks!

**Comment by petecooper** [comment]
Done: https://github.com/textpattern/textpattern/pull/492

**Pull request closed without merging**
