### PR TITLE
Fixes $this in static Skin related methods

### PR DESCRIPTION
**Pull request by NicolasGraph**
Changes proposed in this pull request:

- keep `setDir()` static but do not return `$this`;
- make `resetEditing()` an object related method to support `$this`.

Note that both methods are protected and not in use for now so they are not that useful…

### CODE REVIEW

**Comment by philwareham** [comment]
@Bloke is this PR still valid? Thanks.

**Comment by Bloke** [comment]
I think so. The only reason I didn't merge it before was because it had conflicts. Looks like Nicolas resolved them so it's probably okay to merge.

**Comment by NicolasGraph** [comment]
> Looks like Nicolas resolved them so it's probably okay to merge.

Yes, conflicts were fixed.

**Comment by Bloke** [comment]
Thank you. Merged.

**Pull request merged**
