### PR TITLE
tidy up & fix empty theme commentary

### PR DESCRIPTION
**Pull request by petecooper**
first pass at https://github.com/textpattern/textpattern/issues/1766

Changes proposed in this pull request:

- Tidy up
- Remove erroneous references
- Remove links to specific tags in favour of docs landing page

Requesting review from @Bloke or @bloatware since it's PHP territory and the array escaping might not be best practice.

### CODE REVIEW

**Comment by Bloke** [comment]
All looks good to me, thank you. Are we targeting this for the `dev` branch then? Since it's such a minor change it could be merged into 4.8.8 first, then get merged into dev as part of the regular sync process.

**Comment by petecooper** [comment]
4.8.8 probably best - I can do manual sync up if that's easier, I wasn't sure how PRs are applied to branches.

**Comment by Bloke** [comment]
I think you can target a PR to a particular branch in the same way you can against `dev` - just pick the branch first. Never tried it though. Doing it that way - going "up" from a release-ish branch to dev - just means less chance of conflicts when the release branches are periodically merged to dev.

**Comment by petecooper** [comment]
All sorted, wanted to be sure I didn't tonk it in the process so it took a few more mins.

**Pull request merged**
