### PR TITLE
Add support for images in SVG format

### PR DESCRIPTION
**Pull request by osadl**
SVG support could easily be added by providing some short wrappers to the related GD library functions.

### CODE REVIEW

**Review by bloatware — CHANGES_REQUESTED** [review]
Thank you. I wouldn't check for `<script />` tag here, because it does not protect against various `on*` events xss, and an admin must know what he is doing anyway. But it would be nice to extract stand-alone `<svg />` images from `$content`, which otherwise could be a general type xml.

**Comment by osadl** [comment]
Created various versions of encapsulated SVGs for testing such as

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<html>
<head>
</head>
<body>
<svg>
...
</svg>
</body>
</html>

Both full image and thumb had in all test cases the encapsulation removed, and the only remaining tree element was <svg>. Is this what you wanted me to implement?

**Comment by osadl** [comment]
My test cases were for example
```
<html>
<head>
</head>
<body>
<svg>
  [..]
</svg>
</body>
</html>
```

**Comment by bloatware** [comment]
Yes, thank you, this will be more robust when displaying svg images via `` tag.

Awaiting @Bloke opinion, but all this makes me think that acceptable image formats are too tightly integrated in core. There should be a way to pluginify it.

**Comment by bloatware** [comment]
So, ready for the prime time? @Bloke?

**Comment by Bloke** [comment]
If everyone else is happy, I'm fine with it. I haven't tested it owing to a lack of SVG files knocking around.

I say merge it and we'll deal with anything that crops up in wider testing. Many thanks, @osadl

**Pull request merged**
