### PR TITLE
Show `last_update_check` in detailed diagnostics

### PR DESCRIPTION
**Pull request by makss**
Issue #942

### CODE REVIEW

**Comment by Bloke** [comment]
@makss Does this change still work for people who upgrade from older versions that have a serialized array stored in prefs?

**Comment by makss** [comment]
Yes, it will work.

**Comment by makss** [comment]
btw, when upgrading, this value is [deleted](https://github.com/textpattern/textpattern/blob/adec4dcf26eddb3f9953a04da2041ce44e7bfbb0/textpattern/update/_update.php#L78)

**Comment by Bloke** [comment]
@makss: Ah yes, I'd forgotten about deleting that pref on upgrade. Brilliant, your method is much neater, thank you.

**Pull request merged**
