### PR TITLE
Textapcks ini

### PR DESCRIPTION
**Pull request by bloatware**
Ready to merge?

### CODE REVIEW

**Comment by Bloke** [comment]
Yeah, let's do it. Seems to work well.

**Comment by philwareham** [comment]
Yep please, means I can update the Textpack repo and get the new files into Crowdin for translators.

**Comment by makss** [comment]
+1

**Comment by makss** [comment]
A double-quote bug. Table `txp_lang`:

| id | lang|name | event | owner | data | lastmod |
| --- | --- | --- | --- | --- | --- | --- |
| 1413 | en | textpattern_update_available | diag | | `Format according to <abbr title=\"Greenwich Mean Time\">GMT</abbr> time?` | 2017-11-24 19:05:14 |
| 1605 | en | comment_nofollow | prefs | | `Apply <code>rel=\"nofollow\"</code> to comments?` | 2017-11-24 19:05:14 |
| 1665 | en | send_lastmod | prefs | | `Send \"Last-Modified\" header?` | 2017-11-24 19:05:14 |

**Pull request merged**
