### PR TITLE
Remove textgarden.org link and About section from new installs

### PR DESCRIPTION
**Pull request by petecooper**
Supersedes https://github.com/textpattern/textpattern/pull/491

### CODE REVIEW

**Comment by philwareham** [comment]
Bye bye 'About' section. I've considered it in the past and refrained, but what the heck - lets do it.

Thanks.

**Comment by petecooper** [comment]
Is it worthy of a README mention?

**Comment by philwareham** [comment]
Probably, yes.

**Comment by philwareham** [comment]
By which I mean the changelog file.

**Comment by petecooper** [comment]
I take dibs, or you want it?

**Comment by petecooper** [comment]
I'll do it. I'm feeling saucy and power-crazy.

**Comment by philwareham** [comment]
Lol. If you also amend the public theme I will merge. You'll find comments within the Sass files.

**Comment by petecooper** [comment]
Done: https://github.com/textpattern/textpattern/pull/493

**Pull request merged**
