### PR TITLE
Textpattern admin directory relabelled

### PR DESCRIPTION
**Pull request by philwareham**
Fixes #467

### CODE REVIEW

**Comment by jools-r** [comment]
Phil, looks good but commit [#94ffa17](https://github.com/textpattern/textpattern/pull/648/commits/94ffa17169aebb75879acdb7636120ffcfa39098) has a minor implication for the multi-site directory, easily resolved with two minor corresponding changes in the multi-site directory:

- add a symlink from `admin-themes` to `../../../textpattern/admin-themes` in the [sites/site1/admin/](https://github.com/textpattern/textpattern/tree/master/sites/site1/admin) directory,
- and delete the `themes` symlink.

From my initial testing, it seems to work fine after that...

**Comment by philwareham** [comment]
Ok thanks, I will fix this

**Comment by philwareham** [comment]
Should be fixed now - let me know if not. Cheers!

**Comment by jools-r** [comment]
Thanks!

**Pull request merged**
