### PR TITLE
Add class attribute to comment form tags

### PR DESCRIPTION
**Pull request by jools-r**
This one's an easy addition that makes no changes to existing behaviour.

37efcc2 adds the ability to add custom classes to comment form tags including:

– comment_name_input (and comment_email_input and comment_web_input)
– comment_message_input
– comment_remember (label only as checkbox function won’t take a class attribute)
– comment_preview
– comment_submit

All existing classes are preserved, as is existing warning class behaviour. The changes just splice cleaned class names into the class attribute.

*(Apologies for all the merge branch commits. Only taghandlers.php is actually changed. If cleaner than a PR just port across the changes to that one file as a regular commit.)*

### CODE REVIEW

**Comment by Bloke** [comment]
Great idea, thank you. I'll take this and merge in the changes to 'taghandlers.php' to save injecting all the merge commits.

**Comment by philwareham** [comment]
Looks fine to me, thanks. Will merge.

**Comment by Bloke** [comment]
Or maybe I won't :)

**Comment by philwareham** [comment]
Oops, just seen Stef's comment after merge. Oh well :)

**Comment by Bloke** [comment]
No biggie. I was thinking of running a forum poll to see who could guess when our 10,000th commit would hit core, and by whom. Jools' patch just bypassed that!

**Comment by philwareham** [comment]
🤦‍♂️ sorry - thought Git would ignore that merges from dev into remote branch snd not count them as multiple commits. We live and learn.

**Comment by Bloke** [comment]
Hehe, no worries. git is smart but ultimately does what it's told!

**Comment by jools-r** [comment]
Brilliant. Thanks all!

**Pull request merged**
