### PR TITLE
Configure web access to /textpattern folder

### PR DESCRIPTION
**Pull request by makss**
Discussion of the Issue #796 

ToDo: remove file `/textpattern/css.php`

### CODE REVIEW

**Comment by bloatware** [comment]
I have tried it, but was denied all admin-side access.

**Comment by makss** [comment]
@bloatware  , please try again.

**Comment by bloatware** [comment]
Thanks, but this still looks too restrictive. In particular, some plugins could break (see [this comment](https://github.com/textpattern/textpattern/issues/796#issuecomment-252899898))

**Comment by makss** [comment]
@Bloke 
> Yeah, it would break MLP for starters.

I have installed Textpattern: 4.7.0-dev, then install [MLP](https://github.com/bloke/mlp/tree/v4.6.0) plugin.
(I had a little to correct Textpattern code to the plugin has started)

MLP plugin correctly makes web requests through `textpattern/index.php`
I have not seen direct web requests to the other php file.

I did not see the problems associated with my pull request. Correct me if I'm wrong.

**Comment by bloatware** [comment]
> I did not see the problems associated with my pull request. Correct me if I'm wrong.

We can not exclude that some plugin (image processing, polls, etc...) will need to initiate a browser request (say, ajax) to external php files. @Bloke could say more about MLP, but I have already met such situations. I'm not sure an average user would be able to adapt `.htaccess` in this case.

**Comment by bloatware** [comment]
`css.php` is removed, thanks. New `.htaccess` would need adding `rpc/index.php` exception, but I would rather close the request. @makss ?

**Comment by makss** [comment]
> New `.htaccess` would need adding `rpc/index.php` exception, but I would rather close the request.

This pull request sets web access only to the folder `/textpattern`, `/rpc` is outside.

Yes, close.

**Pull request closed without merging**
