### PR TITLE
Fix issue #261: Reduce load_lang memory usage. 

### PR DESCRIPTION
**Pull request by vanmelick**
This applies the parts of the patch in issue #261 that result in reduced memory usage. The remainder of the patch in that issue was rejected, so applying this one would close that issue.
It also removes the unneeded "empty" call.

### CODE REVIEW

**Comment by vanmelick** [comment]
Seems the 'empty' call was needed after all (#103), so it's back in there. 

What surprises me is that the optimization proposed in this pull request used to be part of TXP in the past, but somehow got removed along the way. Any reason for using safe_rows instead of safe_rows_start+nextRow here? In other places (like get_prefs) this isn't done (optimized safe_rows_start+nextRow) is used there.

**Comment by makss** [comment]
Some convoluted code in function `load_lang()`.
Probably it is necessary replace
```
function load_lang($lang, $events = null)
{
    if ($events === null && txpinterface != 'admin') {
        $events = array('public', 'common');
    }
    $where = '';
    if ($events) {
        $where .= ' and event in('.join(',', quote_list((array) $events)).')';
    }
    foreach (array($lang, 'en-gb') as $lang_code) {
        $rs = safe_rows_start('name, data', 'txp_lang', "lang='".doSlash($lang_code)."'".$where);
        if (!empty($rs)) {
            break;
        }
    }
    $out = array();
    if (!empty($rs)) {
        while($a = nextRow($rs)) {
            if (!empty($a['name'])) {
                $out[$a['name']] = $a['data'];
            }
        }
    }
    return $out;
}
```

To:
```
function load_lang($lang, $events = null)
{
    if ($events === null && txpinterface != 'admin') {
        $events = array('public', 'common');
    }
    $out = array();
    $where = '';
    if ($events) {
        $where .= ' and event in('.join(',', quote_list((array) $events)).')';
    }
    foreach (array($lang, 'en-gb') as $lang_code) {
        $rs = safe_rows_start('name, data', 'txp_lang', "lang='".doSlash($lang_code)."'".$where);
        if (!empty($rs)) {
            while($a = nextRow($rs)) {
                if (!empty($a['name'])) {
                    $out[$a['name']] = $a['data'];
                }
            }
            return $out;
        }
    }
}
```

What better use `safe_rows` or `safe_rows_start` - I do not know.

**Comment by makss** [comment]
BTW, what to check `if (!empty($a['name']))`  ?  It may be easier to do this in sql query?

```
$rs = safe_rows_start('name, data', 'txp_lang', "lang='".doSlash($lang_code)."'".$where." and name<>''");
```

**Comment by vanmelick** [comment]
True. That does look better. Patch sent.

**Pull request merged**
