### PR TITLE
Drop Apache 1.x support

### PR DESCRIPTION
**Pull request by petecooper**
Background: http://forum.textpattern.com/viewtopic.php?id=45826

### CODE REVIEW

**Comment by philwareham** [comment]
Since no code has changed, I don't think we need to explicitly state in the README that Apache 1 is not officially support (that would be best suited to mention at documentation repo).

**Comment by petecooper** [comment]
Hmm, OK. Fair point. How about `System requirements` instead of `Changed`?

**Comment by philwareham** [comment]
But nothing actually happened, no code has changed that prevents Apache 1.x from running - or am I missing a previous commit that negates use of Apache 1.x?

**Comment by petecooper** [comment]
You are correct, you're not missing anything - no code change. It's a documented _support_ change.

**Comment by petecooper** [comment]
Yeah, you're right - I'll close.

**Pull request closed without merging**
