### PR TITLE
Make pluggable_ui() chainable

### PR DESCRIPTION
**Pull request by bloatware**
This will make plugins (mainly admin-side UI) collaborate rather than compete.

### CODE REVIEW

**Comment by philwareham** [comment]
I've [opened a branch](https://github.com/textpattern/textpattern/tree/pr/657) for this, with formatting corrections added.

**Comment by bloatware** [comment]
I find this behavior more natural by default (and flexible enough), but if we fancy 100% backwards compatibility, `pluggable_ui()` can call `callback_event()` twice: once as before, and once new way. Plugins that want to merge will then have to `register_callback()` with `$pre = 1`.

**Comment by bloatware** [comment]
This branch has accidentally (sorry!) accumulated parser commits that I'd like to release for testing. If nobody minds, I will merge it.

**Comment by philwareham** [comment]
Fine by me

**Comment by Bloke** [comment]
Suits me.

**Pull request merged**
