### PR TITLE
README tweaks (security, clarity and branding)

### PR DESCRIPTION
**Pull request by petecooper**
A handful of lines hit 80 characters, but this is 2015 so we'll probably be OK.

### CODE REVIEW

**Comment by philwareham** [comment]
Thanks Pete, I'll sort any 80 character lines here.

**Comment by petecooper** [comment]
Thanks, Phil. For reference, what's the ideal upper limit for line length?

**Comment by philwareham** [comment]
Oh, 80 characters is the limit we aim for - your file was fine as-is.

**Comment by petecooper** [comment]
:thumbsup:

**Pull request merged**
