### PR TITLE
Use JSON file to check for new releases

### PR DESCRIPTION
**Pull request by makss**
Issue #839 

TODO: Need change textpack string `problem_connecting_rpc_server`

### CODE REVIEW

**Comment by philwareham** [comment]
Nice! And fast work too! The only thing I’m thinking is that in the (albeit unlikely) event Textpattern.com domain is lost, it’d be better to use the .io domain here. It points to the same server and file anyway but we own that domain as a team.

**Comment by makss** [comment]
Fixed ;-)

**Comment by philwareham** [comment]
brillisnt, thanks! I’ll test this with a fake version update soon and then we can close the issue. I’ll also note the text pack string change.

**Comment by Bloke** [comment]
And just for completeness: https://github.com/textpattern/textpattern/issues/871#issuecomment-271316405. Although that request has been sidelined (for now), it'd be good if we could expose the date of the last time a version-check attempt was made (in high diagnostics). But if the check fails during the attempt, for whatever reason, just silently fail.

**Comment by makss** [comment]
btw, it seems we had a broken `last_update_check`, now I will fix it.

**Pull request merged**
