### PR TITLE
Update scripts: less chance of errors / abort on error

### PR DESCRIPTION
**Pull request by vanmelick**
See commit messages for details. Goal is to fix issue #573

### CODE REVIEW

**Comment by vanmelick** [comment]
Fixed merge conflicts.

**Comment by jools-r** [comment]
Small postscript: for commit [cf1585c](https://github.com/vanmelick/textpattern/commit/cf1585cd84625b7bcba3adf7f0dbf0b832daf877) (Remove empty update files for version 4.4.0 and 4.4.1), you also need to remove the corresponding checksums on lines [60](https://github.com/textpattern/textpattern/blob/master/textpattern/checksums.txt#L60) and [61](https://github.com/textpattern/textpattern/blob/master/textpattern/checksums.txt#L61) to prevent Admin > Diagnostics showing them as missing.

**Comment by philwareham** [comment]
@vanmelick can you confirm this (see above)?

**Comment by vanmelick** [comment]
Yes. I'll send a pull request soon to correct this.

**Comment by vanmelick** [comment]
See #615

**Pull request merged**
