### PR TITLE
Plugin help as XML

### PR DESCRIPTION
**Pull request by makss**
### Expand the possibilities of plugin help:

* Multilanguage support in help files.
    * Detect the preferred language.
    * Select the language from the available
* Allow use `textile` and `html`
    * Allow mix `textile` and `html` blocks in one help file
* Separate unit for `css` (global for all languages)
* Separate unit for `javascript` (global for all languages)

The idea is still raw, I will be happy to discuss.

### Minimal XML help

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
<help lang="en-gb">
	<item format="textile"><![CDATA[
h3. What do you want to do next?
...
]]></item>
</help>
</resources>
```

### Structure of the XML help
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
<help lang="en-gb">
	<item format="textile"><![CDATA[
h3. What do you want to do next?
...
]]></item>
	<item format="textile"><![CDATA[
h3. Other textile block, why not?
]]></item>
	<item><![CDATA[
<h3>Bulk HTML block</h3>
]]></item>
</help>

<help lang="uk-ua">
	<item format="textile"><![CDATA[
h3. Ukrainian help file
]]></item>
</help>

<css><![CDATA[
.qwerty {
	color: red;
}
]]></css>

<js><![CDATA[
	// js code here
//	alert('qwerty');
]]></js>
</resources>
```

### Example `xml help file`, install the plugin and go to the help section.

```
# Name: aks_help_test v0.1a (compressed)
# Type: Public plugin
# test xml help file
# Author: makss
# URL: http://makss.uaho.net/
# Recommended load order: 5

# .....................................................................
# This is a plugin for Textpattern CMS - http://textpattern.com/
# To install: textpattern > admin > plugins
# Paste the following text into the 'Install plugin' box:
# .....................................................................

H4sIAAAAAAAAA71V/W/iNhj+uf4r3kVIwNQkBO6AhZDqbpt2J3F3k9Zpk9oKmcQhKc5HbedS
VPV/32sntLSrtk7aZgmw34/H78djXup7Y/9O+m98q6A5sxbS9ya+RXdynTJerRWTSgunKKtV
Wgp9eOtbOVpIYz06aNa1yLRkPPatVKnKd11j5dQ0LZ2CKVdrZ771lQmZlYU+4bUjx6MGyPOt
mMlIZJXqtN7ct3QAcJtz0OFAknHW+UVlzDpA14VNnVedQu2rNg/E7qItRcxEJ3vbyRJOt/LY
zkMh5bxs1qnKuUnfWmx8r0Vtj2g1neKNwZkOqUtkaXnOyAJWYEhZsV1atUrsuXUWkkAwWdYi
YhL3JgFOtQEr7O3GCslJkCmWQ1KKnKol5nqrdIJh8M3F9z+8O393QdKJA7+lVEFcwr6soaGF
AlXqY4HWZ4RUgjmQ1EWkqwYVr7dZ0fZOsALTHvRiqugp9FLBkmW/PyR3BHD1ylrBEvr9RXvU
kUkUUCHofjBspVkCg55OdQkyyyvOcL/mJY3XUgnM9QBu/WK0v39a/chZzgplncLq43s8rz9/
MakMh3BHHMcxsPfknpBVJhVC+IR8Czc3+NU0DTEmV1dh4OrKhOSVJfqiUiagU8KGl9HuFJp0
D0Wpa7S5cYzy//0iLyRyFHeQTsL3Nd/Bh/NPqzbmwEXZ8xKgELuJCMcMqnd2TV/NoF93gmZF
RovHV9QR57B6h9otkVcNXH5mKqICCX553iouf6ZCIps6YuiFlzIapcgQjWqHJhIqoac3ut1w
tHptiIhv1HZIFTJoU+P7HgztsNUunroYwCWgXT5oQZ8aGHYecJHKXQ7953c/0N1ZPiRqh93m
PM1kh+4UT/HvGZfsL6C00598yOOO/G0bE2En4qGNz8ixQhMwFi0vSBBnXyHiVErs9G1lb0UW
o7O+7CWVHTHOLbhoslilpyAZ08+ByavwIcagCn9CSzCV9gK36tBchAv/DczxazEhzbYpx4/6
B+iT/yDiN88wSffzci8jKY+65tw0TKg90u8kKnkpfBAsXuCfnfHVtuhyfexxgrPrWoIeZvg2
BSOue0I5ggz6LVYfOW+8r/UMcR8Hih5GOKnz2Ay0CQ7dZDKbziffselo7M3no2g2nW5mo5jO
xtMk9pKxtbj/A5wTpLDvBwAA
```

### CODE REVIEW

**Comment by philwareham** [comment]
Whatever we choose should probably coincide with a rethink of how pophelp itself is stored and displayed. I’m leaning towards storing that in xml format too. @bloke what are your thoughts?

**Comment by NicolasGraph** [comment]
I'm surprised we could safely parse this.

According to this [thread](https://forum.textpattern.io/viewtopic.php?id=47833) and what @gocom and @bloke confirmed, Textile is used in restricted mode to safely parse plugin help files making sure it's free of XSS. As said in the forum, it removes classes, id's, and renders scripts as text. That is why I opened this [issue](https://github.com/textpattern/textpattern/issues/908) and proposed, on @bloke recommendation, [a way to render help files on the fly](https://github.com/NicolasGraph/textpattern/commit/e9fac766bdce81ada8f18f0287cb3a8d7aea6617).

Now, if we can run Textile without the restricted as it seems to be done here; why not…

Finally, while it could be useful to add a multilingual support, for CSS and JS I would prefer to introduce a design consistency as my commit do. It also makes help files creation easier for plugin author, which is nice when you had pretty long files as I do or see on other plugins.

**Comment by philwareham** [comment]
@NicolasGraph getting plugin authors to all follow a consistent design approach is unlikely (although it would be nice in a perfect world). Everyone pretty much does their own thing for help files. All I think we can do is guide them.

Maybe an example help file layout in the [plugin template repo](https://github.com/textpattern/textpattern-plugin-template) would suffice. I probably need to document that repo better anyway.

**Comment by NicolasGraph** [comment]
> Everyone pretty much does their own thing for help files.

Because we let them do it and don't propose something better than a long page of text.
Now if you are still ok to let plugin authors do what they want in the future, what about safety?

**Comment by bloatware** [comment]
Just FWIW, plugin authors already have the ability to do as much harm as they want, either way. I don't see what can be done about it.

**Comment by NicolasGraph** [comment]
Thanks for your reply @bloatware; while it seems to contradict what others replied to me about the Textile restricted mode, I would tend to trust you. Good to know.

**Comment by Bloke** [comment]
Thinking about this further, I'm now confused why we disallow fat Textile in plugin help.

I like the idea of auto-creating a TOC (because it saves space in the user help file and aids navigability).

I also like the idea of XML help files becasue of their multi-lingual capability. But Phil's right: we need to consider this in the grand scheme of how we handle pophelp and language files in general. See #292 and #838 for more.

**Comment by philwareham** [comment]
I'm happy to follow @makss lead on the pophelp files. I have pophelp texts (or will soon have them) as XML files anyway and the setup rewrite uses XML to a large extent so I'm happy to supply in that format (although my pophelp files are purely HTML within XML, not Textile).

So if plugin help can be done in XML too that is fine with me.

**Comment by NicolasGraph** [comment]
> I also like the idea of XML help files because of their multi-lingual capability.

I totally agree about that.

**Comment by makss** [comment]
Can place pophelp in the lang directory:
```
/textpattern/lang/en-gb.txt
/textpattern/lang/en-gb_help.xml
```

### It is possible for a pophelp to use such file format:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>

<help group="admin">
	<item id="add_new_author"><![CDATA[
		<h2>Users: Add new author</h2>
		<p>A password, welcome message and login instructions will be emailed to the new author.</p>
	]]></item>
	<item id="remember_login" format="textile"><![CDATA[
h2. Remember login

When checked, you will remain logged in to your Textpattern account with the current web browser, until you choose to log out. If left unchecked, you will be automatically logged out after a period of inactivity.

Requires cookies to be enabled in your browser.
	]]></item>
</help>

<help group="prefs">
	<item id="admin_side_plugins"><![CDATA[
		<h2>Preferences: Use admin-side plugins?</h2>
		<p>Admin-side plugins can change the operation of the administration interface. They might hook into already existing actions, like editing or publishing articles, or they might add new panels for added/extended functionality.</p>
		<p>If you would like to learn more about admin-side plugins, please see the <a rel="external" target="_blank" href="http://docs.textpattern.io/development/">Extending Textpattern <span class="ui-icon ui-icon-extlink">(opens an external link in a new window)</span></a> page in <a rel="external" target="_blank" href="http://docs.textpattern.io/">Textpattern User Documentation <span class="ui-icon ui-icon-extlink">(opens an external link in a new window)</span></a>. Plugins of all sorts are listed in the <a rel="external" target="_blank" href="http://textpattern.org/">Textpattern Resources <span class="ui-icon ui-icon-extlink">(opens an external link in a new window)</span></a> site.</p>
	]]></item>
	<item id="allow_article_php_scripting"><![CDATA[
		<h2>Preferences: Allow PHP in articles?</h2>
		<p>When enabled, this setting will allow use of PHP within articles. The author must have sufficient privileges to do so (by default, only <a rel="external" target="_blank" href="http://docs.textpattern.io/administration/user-roles-and-privileges">‘Publishers’ <span class="ui-icon ui-icon-extlink">(opens an external link in a new window)</span></a> and <a rel="external" target="_blank" href="http://docs.textpattern.io/administration/user-roles-and-privileges">‘Managing Editors’ <span class="ui-icon ui-icon-extlink">(opens an external link in a new window)</span></a> can).</p>
		<p>PHP code must have opening and closing PHP tags omitted, and also be enclosed within <a rel="external" target="_blank" href="http://docs.textpattern.io/tags/php"><code>&lt;txp:php&gt;</code> tags <span class="ui-icon ui-icon-extlink">(opens an external link in a new window)</span></a>.</p>
	]]></item>
</help>
</resources>
```
`<help group="admin">`  - Grouping for easy editing. Perhaps later we will want to deduce the total assistance by sections, such a grouping will be useful to us. Sense to describe the attributes language code - no, we have one file - one language.


`<item id="admin_side_plugins">` or `<item id="remember_login" format="textile">` - Allow use any format help: html, Textile, possible Markdown, etc.

Can also provide an optional attribute `title`, for the subsequent auto-building of TOC.
`<help group="admin" title="Admin section help">`.
`<item id="admin_side_plugins" title="Preferences: Use admin-side plugins?">`

**Comment by philwareham** [comment]
@makss yes I can make the pophelp files follow that format. I've opened an issue in that repo to track that, and will provide some test files when I can.

**Comment by philwareham** [comment]
OK, [this commit](https://github.com/textpattern/textpattern/commit/22105efe7a5f6967e3ece7ef446a3cecf0c74c66) introduces an XML file for the `en-gb` language in the structure @makss suggested.

**Comment by makss** [comment]
WOW, how fast!

**Comment by Bloke** [comment]
So we're going with one pophelp file per language? Cool.

In which case, phase one of implementing this is pretty much just a case of changing the pophelp function to remove the link to RPC when displaying pophelp in the popup window and instead read it from the `{current-UI-language}_help.xml` file. Find the appropriate node in there, assume HTML is the `format` unless otherwise stated and render it.

That removes RPC completely from the loop. We can then, as phase two, look at removing the actual popup window (if necessary) and making it a modal or slide-out drawer, or whatever UX we want.

If so, does anybody want to merge `dev` into `languages-inclusion` and start phase one in that branch?

**Comment by philwareham** [comment]
Obviously I can help out with phase 2 of Stef’s plan (replaced by the pop up windows with something better) but someone else will need to do the php programming stuff.

I think RPC is still used for version update checks too, as well as textpacks and help files. Not sure if anything else relies on it.

**Comment by makss** [comment]
@Bloke, Yes, quite right.

I think it would be convenient to create a help subsystem: `?event=help`

* `?event=help&step=pophelp` - Probably need to rename `{current-UI-language}_pophelp.xml`
    * first stage is a simple replacement of rpc.
    * second stage is Ajax to some element of design.

If we get the autocreation of TOC and navigation, then we can further expand the help subsystem:

* `?event=help&step=plugin_help` - Move and extend plugin help.
* `?event=help&step=theme_help`
* `?event=help&step=txp_help` - Short offline Textpattern help `{current-UI-language}_help.xml`
* `?event=help&step=custom_help` - Allow web developers to register and display their help file. For example, it will be convenient to leave the instruction to users.
* `?event=help&step=dashboard` - List of all available help files. Can add this list to the navigation menu.

I would like to do this. What can be realized from this - it will be seen later. ;)

**Comment by vanmelick** [comment]
On 06/07/17 15:16, makss wrote:
>
> Expand the possibilities of plugin help:
>

Would anyone mind fixing the current functionality as described here 
first ;)
https://forum.textpattern.io/viewtopic.php?pid=306165#p306165

--Ruud

**Comment by Bloke** [comment]
> Would anyone mind fixing the current functionality

[Done](https://github.com/textpattern/textpattern-plugin-template/commit/c2fb187698aadedf47f23bd80476794ecf626402). Thank you.

**Comment by Bloke** [comment]
@makss Thanks, that'd be great. Let's fold in support for the auto-TOC that Nicolas wrote and move on from there. I'll do that in the languages-inclusion branch as well, since it's kind of related.

Can we get away without the extra `_help` in the `step` since the event has already covered that aspect of it? viz:

```
?event=help&step=plugin
?event=help&step=theme
...
```

And yes, sorry @philwareham, I meant that it removes RPC completely from the help system. We still need to do the JSON version check file thing: Issue #839.

**Comment by makss** [comment]
* first stage is a simple replacement of rpc  -  [Done](https://github.com/makss/textpattern/tree/patch-3)  :)

ps: If necessary, I then transfer my code to the desired brunch.

**Comment by makss** [comment]
This patch [was included](https://github.com/textpattern/textpattern/pull/920/commits/d76bf483887a3304ae7e32d15bfb8613e0c5f904) in another patch #920

**Comment by NicolasGraph** [comment]
I can't make the provided example of plugin work properly; it display weird strings, is it normal?
I would like to test plugin help files as XML but I failed untill now with the provided code chunks.
Are there some updates I missed?
Thanks.

**Comment by NicolasGraph** [comment]
Ok, sorry, according to https://github.com/textpattern/textpattern/pull/920, it seems that only popHelp was merged…

**Pull request closed without merging**
