### PR TITLE
default cookie_domain for multisite installs + DS separator

### PR DESCRIPTION
**Pull request by jools-r**
Changes proposed in this pull request:

- If no cookie_domain is given in the config for a multisite installation, assume main domain name. If a regular install, ignore as before.
- Replace `'/'` with `DS` directory separator
- align with current dev

### CODE REVIEW

**Comment by jools-r** [comment]
makss' previous amendments mean that the `/sites` directory can now be placed 'anywhere', e.g. relocated outside of the textpattern repo. Only the symlinks need updating. Commit https://github.com/textpattern/textpattern/pull/1065/commits/3754609c48cf935bc93635760ad550996ce879fd is a first attempt at a pre-install routine for re-symlinking the `/sites/admin` symlinks if the directory is moved to another location.

With this variant, the `/sites` directory can remain where it is as part of the textpattern repo, and it is up to the user to move it somewhere else should they want to.

Basic principle:

* If the `vendor` symlink in the `/sites/admin` folder resolves correctly (wherever it may be), then proceed with the multisite install as before. One never sees the pre-install routine.
_Case: 'standard' /sites location is in use._
_Case: Other /sites location is in use but user has already provided correct symlinks of their own._

* If the  `vendor` symlink does not resolve correctly or is missing, notify the user and ask them to specify the location of the Textpattern root directory.
_Case: User has shifted the /sites directory to another location but has not modified the symlinks, or not copied them correctly._
** If the user provides a wrong txp-root-path, ask them to check it and retry.
** If txp-root-path provided by the user is good, compute relative path and create symlinks with PHP.
*** Test if okay and notify user of the symlinks created -> Proceed with the multisite install as before.
*** If, for some reason, symlinks could not be created, notify and present command-line commands to cut-and-paste (currently unix). Only then can one proceed.

As all of this happens before the installer knows where Textpattern is located, it has no knowledge of Textpattern's language strings or setup styling. Hence the output at this point is largely unstyled and hardcoded in English. This is, however, a fairly rare situation.

Finally, I'm sure you experts can neaten up the code and catch situations I may not have seen.

Tested on mac/unix with /sites directory in various locations. Some locations may be subject to server-side base directory restrictions, but the usual candidates like parallel to the textpattern installation(s) are no problem.
Untested on windows (presumably the cut-and-paste code needs to be different for windows). Testers and advice needed.

**Comment by philwareham** [comment]
How's this PR coming along? Ready to merge or additional work planned? Cheers!

**Comment by jools-r** [comment]
The PR's up to date with the current dev. I added a ‘pre-install’ step ([see above](#issuecomment-351540448)) to try and (semi-)automatically create the symlinks, thereby avoiding the need to shift admin-themes and textpattern.js into the `vendors` directory, but I don't think anyone has reviewed it yet.

One aspect that will require further work (and had to wait until the themes branch was ready) is the 'cascade' from a multisite's `themes` and `admin-themes` folders to the main `themes` and `admin-themes` as [outline by bloke](https://github.com/textpattern/textpattern/commit/c95016cf2d680348d4dcea57764bd05966ecbd70#commitcomment-25940041). I think that probably exceeds my coding 'skillz' so will require input from more capable hands.

**Comment by jools-r** [comment]
Erm, there was one more thing: the setup routine should replace the admin-links in the [default welcome article](https://github.com/textpattern/textpattern/blob/dev/textpattern/setup/articles/articles.welcome.xml) with the correct link destinations. That could happen at the point when that is imported.

**Comment by jools-r** [comment]
The branch in my PR is now up to date with the current dev including themes. There's currently no theme-cascade mechanism from the multisite to the main textpattern directory (that would need building into the theme import/export mechanism) but you can presently have themes support either:
- on a per-site basis by placing *a themes folder* (with .htaccess) in the respective `sites/sitename/public/` folder. This is what I've done at present (see 0af6cdb).
- using themes in the central /textpattern installation by creating *a symlink* to the themes folder in the  `sites/sitename/public/` folder.

I refactored the pre-install step to cater for the ability to create symlinks in both the `/admin` and/or `/public` directories. The /themes folder symlink is in the code but currently commented out (see 0af6cdb).

I also added output of copy-and-pastable command line code for creating symlinks in windows (as well as linux as was previously the case) in the event that php cannot create the symlinks. *I've not been able to test this, though* on windows.

**Comment by philwareham** [comment]
Hi @jools-r - how are we getting on with this? Close to merge or more work required? Cheers!

**Comment by jools-r** [comment]
Just updated it to be in line with Stef's changes from last night. Themes selection and import/export works fine in a multisite constellation now too. As far as I'm concerned, it's ready for testing and code review by the devs. See [my](#issue-279923652) [previous](#issuecomment-351540448) [comments](#issuecomment-357470358) above for the back history.

Todos: 
* Testing (especially pre-install symlinking on windows servers)
* Update setup language strings to include `{configpath}` and `{setuppath}` for proper setup and config messages during setup. I've coded these into my branch for the moment but they need to be fed back into CrowdIn. I can put together a list.
* Add a few language strings for the diagnostics panel. I'll collate these too.
* Issue: Admin-side links in the welcome article are hard-coded to `/textpattern/index.php?…`. If the welcome article can be brought into the DB during installation with an `{admin_path}` placeholder for replacement with the actual link (like the setup language strings), then that could be resolved. This needs the attention of a dev.

**Comment by philwareham** [comment]
Hi @jools-r - please send me a list of all the additional text strings needed and what group they go in, along with full text for each if possible. I can then reconfigured Crowdin. Cheers!

**Comment by jools-r** [comment]
These are the language strings. The first set are simply a matter of replacing `/textpattern/`with `{configpath}` and with `{setuppath}` (installation_preamble) in the **setup language strings** in the `/setup/lang/` folder. They don't need *translating* as such, but not all language strings use the same wording, so some languages lack the /textpattern/ part to replace:

```
[setup]
already_installed="It looks like Textpattern is already installed. If you want to make a clean install, please remove <code>config.php</code> from your <code>{configpath}</code> directory and try again."
create_config="Create a file called <code>config.php</code> in the <code>{configpath}</code> directory and paste the following inside…"
installation_postamble="For security, you should now remove the <code>setup</code> directory from your <code>{setuppath}</code> directory. Please check the Admin Diagnostics panel from time to time for update announcements or troubleshooting hints."
```

The second set are three new strings for the diagnostics panel in the regular languages:

```
[diag]
admin_url="Admin URL"
cookie_domain="Cookie domain"
multisite_root_path="Multisite root"
```

That's all.

**Comment by philwareham** [comment]
OK, I've added the strings/changes to the base English Textpack - I won't sync it to Crowdin or pull to core until this PR is merged though. @Bloke it's over to you for testing and merge decision! :)

**Comment by philwareham** [comment]
It's merged into `multi-site-fix` branch for testing now.

**Pull request merged**
